name: Weekly SKU Update

on:
  workflow_dispatch: {}            # déclenchement manuel
  schedule:
    - cron: "0 2 * * 1"            # tous les lundis 02:00 UTC (modifier si besoin)

jobs:
  run-sku-update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: update-sku
      cancel-in-progress: false

    env:
      SHOP_NAME: ${{ secrets.SHOP_NAME_TEC }}
      ACCESS_TOKEN: ${{ secrets.SHOPIFY_API_TOKEN }}
      # ajoute ici d'autres vars si ton code en a besoin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ----- Option A : exécuter en module (recommandé si 'shopify_sdk' est un package) -----
      - name: Run SKU updater (module)
        if: ${{ always() }}
        run: python -m shopify_sdk.mutations.sku

      # ----- Option B : exécuter le fichier directement (décommente si A échoue) -----
      # - name: Run SKU updater (script)
      #   run: python shopify_sdk/mutations/sku.py

      - name: Upload logs (si présents)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sku-update-logs
          path: |
            **/*.log
            logs/**
          if-no-files-found: ignore
